# local.nix - Machine-specific configuration
# This file is generated by setup.sh and staged in git
# Regenerate with: ./setup.sh or manually edit as needed

{
  system = "aarch64-darwin";
  username = "julien";
  homeDirectory = "/Users/julien";
}
