#!/usr/bin/env bash

set -euo pipefail

# =============================================================================
# Configuration
# =============================================================================

SCRIPT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
FLAKE="$SCRIPT_DIR#mac"
SECRETS_DIR="$HOME/.config/nix-config/local"
SSH_KEY_PATH="$HOME/.ssh/id_ed25519_github"

# =============================================================================
# Logging Functions
# =============================================================================

# Colors (only if terminal supports it)
if [[ -t 1 ]]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[0;33m'
    BLUE='\033[0;34m'
    CYAN='\033[0;36m'
    BOLD='\033[1m'
    DIM='\033[2m'
    RESET='\033[0m'
else
    RED='' GREEN='' YELLOW='' BLUE='' CYAN='' BOLD='' DIM='' RESET=''
fi

log_header() {
    echo ""
    echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${BLUE}  $1${RESET}"
    echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
}

log_section() {
    echo ""
    echo -e "${CYAN}▸ $1${RESET}"
    echo -e "${DIM}──────────────────────────────────────────────────${RESET}"
}

log_info() {
    echo -e "${BLUE}ℹ${RESET}  $1"
}

log_success() {
    echo -e "${GREEN}✓${RESET}  $1"
}

log_warning() {
    echo -e "${YELLOW}⚠${RESET}  $1"
}

log_error() {
    echo -e "${RED}✗${RESET}  $1"
}

log_step() {
    echo -e "${DIM}→${RESET}  $1"
}

# =============================================================================
# Helper Functions
# =============================================================================

prompt_with_default() {
    local prompt_text="$1"
    local default_value="$2"
    local result

    if [[ -n "$default_value" ]]; then
        read -rp "   $prompt_text [$default_value]: " result
        echo "${result:-$default_value}"
    else
        read -rp "   $prompt_text: " result
        echo "$result"
    fi
}

validate_email() {
    local email="$1"
    [[ "$email" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]
}

check_macos() {
    if [[ "$OSTYPE" != "darwin"* ]]; then
        log_error "This script is designed for macOS only"
        exit 1
    fi
}

# =============================================================================
# Installation Functions
# =============================================================================

install_nix() {
    if command -v nix &>/dev/null; then
        log_success "Nix is already installed"
        return 0
    fi

    log_info "Installing Nix..."
    sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install)
    log_success "Nix installed successfully"
}

install_homebrew() {
    # Check if Homebrew is already installed
    if command -v brew &>/dev/null; then
        log_success "Homebrew is already installed"
        return 0
    fi

    # Check common Homebrew locations for Apple Silicon and Intel Macs
    if [[ -x "/opt/homebrew/bin/brew" ]] || [[ -x "/usr/local/bin/brew" ]]; then
        log_success "Homebrew is already installed (not in PATH yet)"
        return 0
    fi

    log_info "Installing Homebrew..."
    sudo NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    # Add Homebrew to PATH for the current session
    if [[ -x "/opt/homebrew/bin/brew" ]]; then
        eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [[ -x "/usr/local/bin/brew" ]]; then
        eval "$(/usr/local/bin/brew shellenv)"
    fi

    log_success "Homebrew installed successfully"
}

enable_flakes() {
    mkdir -p ~/.config/nix
    if grep -q "experimental-features" ~/.config/nix/nix.conf 2>/dev/null; then
        log_success "Flakes already enabled"
    else
        echo "experimental-features = nix-command flakes" >>~/.config/nix/nix.conf
        log_success "Flakes enabled"
    fi
}

generate_local_config() {
    local local_nix="$SCRIPT_DIR/local.nix"
    log_info "Generating local.nix for user: $USER"

    # Detect system architecture
    local arch
    arch=$(uname -m)
    local system
    case "$arch" in
        arm64) system="aarch64-darwin" ;;
        x86_64) system="x86_64-darwin" ;;
        *) 
            log_error "Unsupported architecture: $arch"
            exit 1
            ;;
    esac

    cat >"$local_nix" <<EOF
# local.nix - Machine-specific configuration
# This file is generated by setup.sh and staged in git
# Regenerate with: ./setup.sh or manually edit as needed

{
  system = "$system";
  username = "$USER";
  homeDirectory = "$HOME";
}
EOF

    log_success "Generated local.nix (system=$system, user=$USER)"
}

build_system() {
    log_info "Building system as $(whoami)..."
    FLAKE_DIR="$SCRIPT_DIR" nix build "$SCRIPT_DIR#darwinConfigurations.mac.system" --impure
    log_success "System built successfully"
}

activate_system() {
    log_info "Activating system (requires sudo)..."
    sudo FLAKE_DIR="$SCRIPT_DIR" "$SCRIPT_DIR/result/sw/bin/darwin-rebuild" switch --flake "$FLAKE" --impure
    log_success "System activated"
}

# =============================================================================
# Configuration Functions
# =============================================================================

setup_git_config() {
    log_section "Git Configuration"

    local current_user="${USER:-$(whoami)}"
    local default_email="${current_user}@example.com"

    GIT_USER_NAME=$(prompt_with_default "Your full name (for Git commits)" "")
    while [[ -z "$GIT_USER_NAME" ]]; do
        log_warning "Name cannot be empty"
        GIT_USER_NAME=$(prompt_with_default "Your full name (for Git commits)" "")
    done

    GIT_USER_EMAIL=$(prompt_with_default "Your email address (for Git commits)" "$default_email")
    while ! validate_email "$GIT_USER_EMAIL"; do
        log_warning "Invalid email format, please try again"
        GIT_USER_EMAIL=$(prompt_with_default "Your email address (for Git commits)" "$default_email")
    done

    log_success "Git configuration captured"
}

setup_ssh_key() {
    log_section "SSH Key Generation"

    local generate_ssh="y"

    if [[ -f "$SSH_KEY_PATH" ]]; then
        log_warning "SSH key already exists at $SSH_KEY_PATH"
        read -rp "   Generate a new one anyway? (y/N): " generate_ssh
        generate_ssh="${generate_ssh:-n}"
    fi

    if [[ ! "$generate_ssh" =~ ^[Yy]$ ]]; then
        log_info "Skipping SSH key generation"
        return 0
    fi

    log_info "Generating SSH key for GitHub..."
    ssh-keygen -t ed25519 -C "$GIT_USER_EMAIL" -f "$SSH_KEY_PATH" -N ""
    log_success "SSH key generated at $SSH_KEY_PATH"

    configure_ssh_config
    display_and_copy_ssh_key
    setup_github_ssh
}

configure_ssh_config() {
    local ssh_config="$HOME/.ssh/config"

    if [[ -f "$ssh_config" ]] && grep -q "Host github.com" "$ssh_config"; then
        log_info "SSH config already contains GitHub entry"
        return 0
    fi

    mkdir -p "$HOME/.ssh"
    cat >>"$ssh_config" <<EOF

# GitHub
Host github.com
    HostName github.com
    User git
    IdentityFile $SSH_KEY_PATH
    IdentitiesOnly yes
EOF
    chmod 600 "$ssh_config"
    log_success "SSH config updated"
}

display_and_copy_ssh_key() {
    echo ""
    echo -e "${DIM}──────────────────────────────────────────────────${RESET}"
    echo -e "${BOLD}Your SSH public key:${RESET}"
    echo ""
    cat "$SSH_KEY_PATH.pub"
    echo ""
    echo -e "${DIM}──────────────────────────────────────────────────${RESET}"

    if command -v pbcopy &>/dev/null; then
        pbcopy <"$SSH_KEY_PATH.pub"
        log_success "SSH key copied to clipboard"
    fi
}

setup_github_ssh() {
    if ! command -v open &>/dev/null; then
        echo ""
        log_info "Add this SSH key to GitHub:"
        log_step "Go to: https://github.com/settings/ssh/new"
        log_step "Paste the key above"
        log_step "Click 'Add SSH key'"
        read -rp "   Press Enter when done..."
        return 0
    fi

    log_info "Opening GitHub SSH settings in your browser..."
    open "https://github.com/settings/ssh/new"
    echo ""
    log_info "Instructions:"
    log_step "The SSH key is already copied to your clipboard"
    log_step "Paste it into the 'Key' field on GitHub"
    log_step "Give it a title (e.g., 'MacBook Pro')"
    log_step "Click 'Add SSH key'"
    echo ""
    read -rp "   Press Enter after you've added the key to GitHub..."

    test_github_ssh
}

test_github_ssh() {
    log_info "Testing SSH connection to GitHub..."
    if ssh -T git@github.com -o StrictHostKeyChecking=no 2>&1 | grep -q "successfully authenticated"; then
        log_success "SSH key successfully configured"
    else
        log_warning "SSH test inconclusive - you may need to verify manually"
        log_step "Run: ssh -T git@github.com"
    fi
}

create_secrets_file() {
    log_section "Creating Local Secrets"

    mkdir -p "$SECRETS_DIR"

    cat >"$SECRETS_DIR/secrets.nix" <<EOF
# secrets.nix
# This file is automatically generated by setup.sh
# It contains your personal configuration and is gitignored

{ config, pkgs, ... }:

{
  # Git configuration
  programs.git = {
    userName = "${GIT_USER_NAME}";
    userEmail = "${GIT_USER_EMAIL}";
  };

  # You can add other personal overrides here
}
EOF

    log_success "Secrets file created at $SECRETS_DIR/secrets.nix"
}

apply_personal_config() {
    log_info "Applying configuration with your personal settings..."
    FLAKE_DIR="$SCRIPT_DIR" darwin-rebuild switch --flake "$SCRIPT_DIR#mac" --impure
    log_success "Personal configuration applied"
}

# =============================================================================
# Post-Install Setup
# =============================================================================

setup_github_cli() {
    log_section "GitHub CLI"

    if ! command -v gh &>/dev/null; then
        log_warning "GitHub CLI not available yet - run 'gh auth login' after restart"
        return 0
    fi

    if gh auth status &>/dev/null; then
        log_success "GitHub CLI already authenticated"
        return 0
    fi

    log_info "Authenticating with GitHub..."
    log_step "Choose: GitHub.com → HTTPS → Login with a web browser"
    gh auth login
}

setup_aws_cli() {
    log_section "AWS CLI"

    if ! command -v aws &>/dev/null; then
        log_warning "AWS CLI not available yet - run 'aws configure sso' after restart"
        return 0
    fi

    if [[ -f "$HOME/.aws/config" ]]; then
        log_success "AWS CLI already configured"
        return 0
    fi

    log_info "AWS SSO configuration available"
    read -rp "   Configure AWS now? (y/N): " configure_aws
    if [[ "$configure_aws" =~ ^[Yy]$ ]]; then
        aws configure sso
    else
        log_step "Run 'aws configure sso' later to set up AWS access"
    fi
}

show_final_steps() {
    log_header "Setup Complete"

    echo ""
    log_info "Final steps to complete your setup:"
    echo ""

    echo -e "   ${BOLD}1. Sign in to applications${RESET}"
    log_step "Cursor: Open and sign in to your account"
    if command -v open &>/dev/null; then
        open -a Cursor 2>/dev/null || log_step "(Cursor will be installed shortly)"
    fi

    echo ""
    echo -e "   ${BOLD}2. Start Docker${RESET}"
    log_step "Open Docker Desktop and start the daemon"
    if command -v open &>/dev/null; then
        open -a Docker 2>/dev/null || log_step "(Docker will be installed shortly)"
    fi

    echo ""
    echo -e "   ${BOLD}3. Restart your terminal${RESET}"
    log_step "Close and reopen your terminal to apply all changes"

    echo ""
    echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo -e "${BOLD}${GREEN}  🎉 All done! Enjoy your new setup${RESET}"
    echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
    echo ""
}

# =============================================================================
# Main
# =============================================================================

main() {
    log_header "🚀 Nix Configuration Setup"

    check_macos
    cd "$SCRIPT_DIR"

    # Phase 1: Install Nix
    log_section "Installing Nix"
    install_nix
    enable_flakes

    # Phase 2: Install Homebrew
    log_section "Installing Homebrew"
    install_homebrew

    # Phase 3: Generate local configuration
    log_section "Local Configuration"
    generate_local_config

    # Phase 4: Build and activate system
    log_section "Building System"
    build_system
    activate_system

    # Phase 5: Personal configuration
    mkdir -p "$SECRETS_DIR"
    if [[ -f "$SECRETS_DIR/secrets.nix" ]]; then
        log_section "Personal Configuration"
        log_success "Personal configuration already exists"
        log_step "Edit $SECRETS_DIR/secrets.nix to update"
        log_step "Run: darwin-rebuild switch --flake .#mac --impure"
    else
        log_header "📝 Personal Configuration"
        setup_git_config
        setup_ssh_key
        create_secrets_file
        apply_personal_config
    fi

    # Phase 6: Post-install setup
    log_info "GUI apps (Cursor, Slack, Linear, Docker, Karabiner) managed via nix-darwin"
    setup_github_cli
    setup_aws_cli

    # Done
    show_final_steps
}

main "$@"
